### ISSUE TITLE
Game breaking menu

### ISSUE THREAD

**Issue by NicolBy5** [SmashPhil/Vehicles#40] opened 2021-01-24 07:40 UTC
[ModsConfig.zip](https://github.com/SmashPhil/Vehicles/files/5861727/ModsConfig.zip)

This bug makes only appears the background, the only way to remove this bug is removing this mod from the files.

**To Reproduce**
1. You only need to add this mod with all the previous mods

![Captura de pantalla (2115)](https://user-images.githubusercontent.com/77914519/105624149-ace7e900-5ddc-11eb-9b4a-dba5bf98f49b.png)

**Comment by SmashPhil** [comment] 2021-01-24 07:43
Uhhh what..? There’s not a single thing I can do to resolve this. If this bug was reproduce-able by simply adding the mod to the mod list, it would’ve been high priority and fixed right away.  You’ve provided no logs and no context regarding your mod list... please provide your player log in a pastebin link (since hugslib would not be accessible in this case) or I’ll have to close the issue. Thanks

**Comment by NicolBy5** [comment] 2021-01-24 10:13
Well... I found the real reason of the bug: It was because i didin't update my harmony._. (yeah, im sorry for that:( )
But it still throw me some few red errors.
[Player.log](https://github.com/SmashPhil/Vehicles/files/5861963/Player.log)

**Comment by SmashPhil** [comment] 2021-01-24 18:23
The issues you're having are not explicitly bugs from Vehicles, but problems w/ startup that are occurring across multiple mods. You'll probably want to take this over to troubleshooting in the rimworld discord, or if you can send a hugslib log rather than the player log. I'd like to see what versions of each mod you're using cause you're most definitely having issues with Harmony.

**Comment by SmashPhil** [comment] 2021-01-24 20:50
Gonna close this cause it's not really relevant to vehicles, but if you wanna drop your hugslog in my discord server I can help you resolve this issue. Thanks

**Closed by SmashPhil** 2021-01-24 20:50 UTC
